config/routes.rb
Rails.application.routes.draw do
 ##resources
 resources :tms
 resources :pokemons
 
 resources :users do
    resources :pokemons
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'
  
## for omni
get '/auth/facebook/callback' => 'sessions#create'


   # changing routes to not get confused with naming 
   delete '/logout', to: "sessions#logout"
   get '/signup', to: "users#signup"
   post '/signup', to: "users#create"
   get '/login', to: "sessions#login"
   post '/login', to: "sessions#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  #validations
  validates :name, presence: true


  #associations 
  belongs_to :user # user will be able to create,show,index pokemon user/:user_id/pokemons
  belongs_to :tm   # a pokemon will belong to a TM when eqipped during the create or edit
  

end

app/models/tm.rb
class Tm < ApplicationRecord
    #validations
    validates :name, presence: true
    validates :element, presence: true 
    validates :rarity, presence: true 

    #associations 
    has_many :pokemons 
    has_many :users, through: :pokemons 

    scope :rarity, -> { where(:rarity => 'Very Rare')}
end

app/models/user.rb
class User < ApplicationRecord
    #validations
    validates :email, presence: true, uniqueness: true
    validates :password, length: { minimum: 5 }
    has_secure_password 

    #associations 
    has_many :pokemons
    has_many :tms, through: :pokemons    

    #omni
    
  ###edited for omni
  def self.find_or_create_by_omniauth(auth)
    self.where(email: auth['info']['email']).first_or_create do |user|
        user.password = SecureRandom.hex
        user.email = auth['info']['email']
      end
  end
 
end
  
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?
  
  def redirect_if_not_signed_in
    redirect_to login_path unless logged_in?
  end

  def redirect_if_signed_in
    redirect_to root_path if logged_in?
  end
  private
      
  def logged_in?
        !!session[:user_id] 
    end

    def current_user
      @user = User.find_by_id(session[:user_id]) if logged_in?
   end


 end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :redirect_if_not_signed_in
  before_action :set_user
  before_action :set_pokemon, except: [:index, :new, :create]

  def index #user can view all the pokemon in there group
    @pokemons = @user.pokemons
end


def show # user can look at a specific pokemon
  
end

def new
  @pokemon = Pokemon.new
end

def create #created a new pokemon for the specific user, renders errors if any
  @pokemon = current_user.pokemons.build(pokemon_params)
     if @pokemon.save
       redirect_to user_pokemons_path(current_user)
      else 
        @errors = @pokemon.errors.full_messages
        render :new
      end
    end


def edit
  redirect_to user_pokemons_path(current_user) unless current_user == @user
end

def update
  if @pokemon.update(pokemon_params)
    redirect_to pokemon_path(@pokemon)
  else
    @user = current_user
    @errors = @pokemon.errors.full_messages
    render :edit 
  end
end

      
def destroy
  @pokemon.destroy
  redirect_to root_path
end

private
    def set_user
      @user = User.find_by_id(params[:user_id])
    end

    def set_pokemon
      @pokemon = Pokemon.find_by_id(params[:id])
    end

    def pokemon_params
      params.require(:pokemon).permit(:name, :user_id, :tm_id)
    end
   
end

app/controllers/session_controller.rb
def new  
    @user = User.new
  end

  def create  
    @user = User.find_by(email: user_params[:email])
    if @user && @user.authenticate(user_params[:password])
      session[:user_id] = @user.id
      redirect_to user_##_path(@user)
    else
      render :new
    end
  end

  def destroy 
    session.clear
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def login 
    @user = User.new
  end

  ###edited for omni
      def create
      if auth
        @user = User.find_or_create_by_omniauth(auth)
        session[:user_id] = @user.id
        redirect_to root_path
      else
        @user = User.find_by(email: params[:user][:email])
        if @user && @user.authenticate(params[:user][:password])
          session[:user_id] = @user.id
          redirect_to root_path
        else
          redirect_to login_path
        end
      end
    end
  #######
def logout
  session.delete :user_id
  redirect_to root_path
end


private
def user_params
  params.require(:user).permit(:email, :password)
end

  def auth
  request.env['omniauth.auth']
  end
end

app/controllers/tms_controller.rb
class TmsController < ApplicationController

  
    def index #a user will be able to view all avaliable TMs and there attributes
        @tms = Tm.all
    end

    def new
        #seeded in finite TMS. Not apart of project requirements to have a user be able to create 
        #a TM. 
    end

    def create
    # see above 
  end

      def show 
        @tm = Tm.find(params[:id])
      end
    
      def edit
      end
    
    
private
def tm_params
    params.require(:tm).permit(:name, :type, :rarity, )
  end
end

 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_signed_in
  def show
  end
  
  def signup 
      @user = User.new
    end
  
    def create
      @user = User.create(user_params)
      if @user.id == nil 
        @errors = @user.errors.full_messages
        render :signup
      else
        session[:user_id] = @user.id
        redirect_to root_path
      end
    end
     
  

  
    private
      def user_params
        params.require(:user).permit(:trainer, :email, :password)
      end
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    
    def index
       
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/tms_helper.rb
module TmsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokeTm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/_form.html.erb
<% if @pokemon.errors.any? %>
<% @errors.each do |message| %>
  <li><%= message %></li>
<% end %>
<% end %>

<%= form_for @pokemon do |f| %>
<ol>
<li>
<%= f.label :name, "Name" %>
<%= f.text_field :name%> 
</li>
<li>
<%= f.label :tm_id, "Equip a TM:" %>
<%= f.collection_select :tm_id, Tm.all, :id, :name %> 
</li>
</ol>
<br>
<%= f.submit "Submit" %>
<% end %> 

app/views/pokemons/edit.html.erb
<%= render 'welcome/form' %>
<div class='welcome-page'>
<% if @pokemon.user == @user %>
<h2> Edit </h2> 
<%= render 'form' %>
<% else %> 

<p> this is not your pokemon that you are trying to edit. Please return home.</p> 
<%= link_to "Return Home", root_path %>

<% end %> 
</div>

app/views/pokemons/index.html.erb
  <%= render 'welcome/form' %>
  <div class='welcome-page'>
    <h2> Here is your current Pokemon group </h2> 

   <% @pokemons.each do |pokemon| %>
    <li>
      <%= link_to pokemon.name, user_pokemon_path(@user, pokemon)%>
    </li>
   <% end %>
  </div>

app/views/pokemons/new.html.erb
<%= render 'welcome/form' %>
<div class='welcome-page'>
<h2> Add a new Pokemon to your group: </h2> 

<%= render 'form' %>

</div>

app/views/pokemons/show.html.erb
  <%= render 'welcome/form' %>
  <div class='welcome-page'>
  <h2><%= @pokemon.name%> </h2>
  
  <p>TM name: <%= @pokemon.tm.name %></p>
  <p>TM type: <%= @pokemon.tm.element %> </p>
 <p>TM rarity: <%= @pokemon.tm.rarity %> </p>
 
 <br>
<% if current_user == @user %>
<%= link_to "Edit ✏️", edit_user_pokemon_path(@pokemon)%> <br>
<%= link_to "Abandon this pokemon🗑️", user_pokemon_path(@user, @pokemon), method: "delete" %>
  <% end %>
<br>

</div>

app/views/tms/_form.html.erb
<body>
  <div class='welcome-page'>
    <%= render 'welcome/form' %>
    <h2> Here are all avaliable TMS in this database </h2> 

    <table> 
        <tr>
          <th>Name</th>
          <th>Type</th>
          <th>Rarity</th> 
        </tr>
        <% @tms.each do |tm| %>
        <tr>
          <td><%= tm.name %></td>
          <td><%= tm.element %> </td>
          <td><%= tm.rarity %> </td>
        </tr>
        <% end %>
    </table>

 
    <p>** listed as very rare: </p> 
      <% @tms.rarity.each do |tm| %> 
        <ul>
          <li> <%= tm.name %> </li>
          </ul>
      <%  end %> 
 
    <br> 
  </div>
</body>

app/views/tms/index.html.erb
<%= render 'form' %>

app/views/users/new.html.erb
<h1> Sign up ! </h1> 
<%= form_for @user do |f| %>
    <%= f.label :trainer %>
    <%= f.text_field :trainer %> <br>
    <%= f.label :email %>
    <%= f.email_field :email %><br>
    <%= f.label :password%>
    <%= f.password_field :password %><br>
 
    <%= f.submit %>
 <% end %> 

app/views/users/signup.html.erb
  <div class="welcome-page">
  <%= render 'welcome/form' %>
    <h2><u>Sign up</u></h2>
    <% if @user.errors.any? %>
      <% @errors.each do |message| %>
        <li><%= message %></li>
      <% end %>
    <% end %>
    
  
      <%= form_for @user do |f| %>
      <ul>
        <li>
          <%= f.label :trainer %>
          <%= f.text_field :trainer %> 
        </li>
        <li>
          <%= f.label :email %>
          <%= f.email_field :email %>
        </li>
        <li>
          <%= f.label :password%>
          <%= f.password_field :password %><br>
        </li>
        <%= f.submit %>
      </ul>
    <% end %> 
  </div>
   

app/views/welcome/_form.html.erb
<div class='welcome-page'>
    <h1><%= link_to "Poke⚡TM", root_path %>
    </h1>
</div>

app/views/welcome/index.html.erb
<body>
  <% if logged_in? %>
    <div class="welcome-page">
    <%= render 'welcome/form' %>
    <h2>Welcome, Choose an action</h2>
    <ol>
      <li> <%= link_to 'Add a pokemon to your group', new_user_pokemon_path(current_user)%> </li> 
      <li> <%= link_to "View your pokemon", user_pokemons_path(current_user) %> </li>  
      <li> <%= link_to 'View all avaliable TMs', tms_path %> </li>
      <li> <%= link_to  "Logout", logout_path, method: :delete %> </li>
    </ol>
    </div>
  <% else %> 
    <div class='welcome-page'>
    <%= render 'welcome/form' %>
      <ol>
        <li> <%= link_to "Login", login_path %> </li>
        <li> <%= link_to "Sign in with Facebook", "/auth/facebook"%></li> 
        <li> <%= link_to 'Signup', signup_path %> </li> 
      </ol>
    </div>
  <% end %>

</body>